// Generated from ActiveSupport 7.2 TimeZone.all, as OG lists them.
// Each zone: the label OG shows, the API name the API stores, and the IANA zone GET /users/settings returns.
type RailsTimeZone = { readonly label: string; readonly name: string; readonly iana: string };

export const railsTimeZones: ReadonlyArray<RailsTimeZone> = [
  { label: '(GMT-12:00) International Date Line West', name: 'International Date Line West', iana: 'Etc/GMT+12' },
  { label: '(GMT-11:00) American Samoa', name: 'American Samoa', iana: 'Pacific/Pago_Pago' },
  { label: '(GMT-11:00) Midway Island', name: 'Midway Island', iana: 'Pacific/Midway' },
  { label: '(GMT-10:00) Hawaii', name: 'Hawaii', iana: 'Pacific/Honolulu' },
  { label: '(GMT-09:00) Alaska', name: 'Alaska', iana: 'America/Juneau' },
  { label: '(GMT-08:00) Pacific Time (US & Canada)', name: 'Pacific Time (US & Canada)', iana: 'America/Los_Angeles' },
  { label: '(GMT-08:00) Tijuana', name: 'Tijuana', iana: 'America/Tijuana' },
  { label: '(GMT-07:00) Arizona', name: 'Arizona', iana: 'America/Phoenix' },
  { label: '(GMT-07:00) Mazatlan', name: 'Mazatlan', iana: 'America/Mazatlan' },
  { label: '(GMT-07:00) Mountain Time (US & Canada)', name: 'Mountain Time (US & Canada)', iana: 'America/Denver' },
  { label: '(GMT-06:00) Central America', name: 'Central America', iana: 'America/Guatemala' },
  { label: '(GMT-06:00) Central Time (US & Canada)', name: 'Central Time (US & Canada)', iana: 'America/Chicago' },
  { label: '(GMT-06:00) Chihuahua', name: 'Chihuahua', iana: 'America/Chihuahua' },
  { label: '(GMT-06:00) Guadalajara', name: 'Guadalajara', iana: 'America/Mexico_City' },
  { label: '(GMT-06:00) Mexico City', name: 'Mexico City', iana: 'America/Mexico_City' },
  { label: '(GMT-06:00) Monterrey', name: 'Monterrey', iana: 'America/Monterrey' },
  { label: '(GMT-06:00) Saskatchewan', name: 'Saskatchewan', iana: 'America/Regina' },
  { label: '(GMT-05:00) Bogota', name: 'Bogota', iana: 'America/Bogota' },
  { label: '(GMT-05:00) Eastern Time (US & Canada)', name: 'Eastern Time (US & Canada)', iana: 'America/New_York' },
  { label: '(GMT-05:00) Indiana (East)', name: 'Indiana (East)', iana: 'America/Indiana/Indianapolis' },
  { label: '(GMT-05:00) Lima', name: 'Lima', iana: 'America/Lima' },
  { label: '(GMT-05:00) Quito', name: 'Quito', iana: 'America/Lima' },
  { label: '(GMT-04:00) Atlantic Time (Canada)', name: 'Atlantic Time (Canada)', iana: 'America/Halifax' },
  { label: '(GMT-04:00) Caracas', name: 'Caracas', iana: 'America/Caracas' },
  { label: '(GMT-04:00) Georgetown', name: 'Georgetown', iana: 'America/Guyana' },
  { label: '(GMT-04:00) La Paz', name: 'La Paz', iana: 'America/La_Paz' },
  { label: '(GMT-04:00) Puerto Rico', name: 'Puerto Rico', iana: 'America/Puerto_Rico' },
  { label: '(GMT-04:00) Santiago', name: 'Santiago', iana: 'America/Santiago' },
  { label: '(GMT-03:30) Newfoundland', name: 'Newfoundland', iana: 'America/St_Johns' },
  { label: '(GMT-03:00) Brasilia', name: 'Brasilia', iana: 'America/Sao_Paulo' },
  { label: '(GMT-03:00) Buenos Aires', name: 'Buenos Aires', iana: 'America/Argentina/Buenos_Aires' },
  { label: '(GMT-03:00) Montevideo', name: 'Montevideo', iana: 'America/Montevideo' },
  { label: '(GMT-02:00) Greenland', name: 'Greenland', iana: 'America/Godthab' },
  { label: '(GMT-02:00) Mid-Atlantic', name: 'Mid-Atlantic', iana: 'Atlantic/South_Georgia' },
  { label: '(GMT-01:00) Azores', name: 'Azores', iana: 'Atlantic/Azores' },
  { label: '(GMT-01:00) Cape Verde Is.', name: 'Cape Verde Is.', iana: 'Atlantic/Cape_Verde' },
  { label: '(GMT+00:00) Casablanca', name: 'Casablanca', iana: 'Africa/Casablanca' },
  { label: '(GMT+00:00) Dublin', name: 'Dublin', iana: 'Europe/Dublin' },
  { label: '(GMT+00:00) Edinburgh', name: 'Edinburgh', iana: 'Europe/London' },
  { label: '(GMT+00:00) Lisbon', name: 'Lisbon', iana: 'Europe/Lisbon' },
  { label: '(GMT+00:00) London', name: 'London', iana: 'Europe/London' },
  { label: '(GMT+00:00) Monrovia', name: 'Monrovia', iana: 'Africa/Monrovia' },
  { label: '(GMT+00:00) UTC', name: 'UTC', iana: 'Etc/UTC' },
  { label: '(GMT+01:00) Amsterdam', name: 'Amsterdam', iana: 'Europe/Amsterdam' },
  { label: '(GMT+01:00) Belgrade', name: 'Belgrade', iana: 'Europe/Belgrade' },
  { label: '(GMT+01:00) Berlin', name: 'Berlin', iana: 'Europe/Berlin' },
  { label: '(GMT+01:00) Bern', name: 'Bern', iana: 'Europe/Zurich' },
  { label: '(GMT+01:00) Bratislava', name: 'Bratislava', iana: 'Europe/Bratislava' },
  { label: '(GMT+01:00) Brussels', name: 'Brussels', iana: 'Europe/Brussels' },
  { label: '(GMT+01:00) Budapest', name: 'Budapest', iana: 'Europe/Budapest' },
  { label: '(GMT+01:00) Copenhagen', name: 'Copenhagen', iana: 'Europe/Copenhagen' },
  { label: '(GMT+01:00) Ljubljana', name: 'Ljubljana', iana: 'Europe/Ljubljana' },
  { label: '(GMT+01:00) Madrid', name: 'Madrid', iana: 'Europe/Madrid' },
  { label: '(GMT+01:00) Paris', name: 'Paris', iana: 'Europe/Paris' },
  { label: '(GMT+01:00) Prague', name: 'Prague', iana: 'Europe/Prague' },
  { label: '(GMT+01:00) Rome', name: 'Rome', iana: 'Europe/Rome' },
  { label: '(GMT+01:00) Sarajevo', name: 'Sarajevo', iana: 'Europe/Sarajevo' },
  { label: '(GMT+01:00) Skopje', name: 'Skopje', iana: 'Europe/Skopje' },
  { label: '(GMT+01:00) Stockholm', name: 'Stockholm', iana: 'Europe/Stockholm' },
  { label: '(GMT+01:00) Vienna', name: 'Vienna', iana: 'Europe/Vienna' },
  { label: '(GMT+01:00) Warsaw', name: 'Warsaw', iana: 'Europe/Warsaw' },
  { label: '(GMT+01:00) West Central Africa', name: 'West Central Africa', iana: 'Africa/Algiers' },
  { label: '(GMT+01:00) Zagreb', name: 'Zagreb', iana: 'Europe/Zagreb' },
  { label: '(GMT+01:00) Zurich', name: 'Zurich', iana: 'Europe/Zurich' },
  { label: '(GMT+02:00) Athens', name: 'Athens', iana: 'Europe/Athens' },
  { label: '(GMT+02:00) Bucharest', name: 'Bucharest', iana: 'Europe/Bucharest' },
  { label: '(GMT+02:00) Cairo', name: 'Cairo', iana: 'Africa/Cairo' },
  { label: '(GMT+02:00) Harare', name: 'Harare', iana: 'Africa/Harare' },
  { label: '(GMT+02:00) Helsinki', name: 'Helsinki', iana: 'Europe/Helsinki' },
  { label: '(GMT+02:00) Jerusalem', name: 'Jerusalem', iana: 'Asia/Jerusalem' },
  { label: '(GMT+02:00) Kaliningrad', name: 'Kaliningrad', iana: 'Europe/Kaliningrad' },
  { label: '(GMT+02:00) Kyiv', name: 'Kyiv', iana: 'Europe/Kiev' },
  { label: '(GMT+02:00) Pretoria', name: 'Pretoria', iana: 'Africa/Johannesburg' },
  { label: '(GMT+02:00) Riga', name: 'Riga', iana: 'Europe/Riga' },
  { label: '(GMT+02:00) Sofia', name: 'Sofia', iana: 'Europe/Sofia' },
  { label: '(GMT+02:00) Tallinn', name: 'Tallinn', iana: 'Europe/Tallinn' },
  { label: '(GMT+02:00) Vilnius', name: 'Vilnius', iana: 'Europe/Vilnius' },
  { label: '(GMT+03:00) Baghdad', name: 'Baghdad', iana: 'Asia/Baghdad' },
  { label: '(GMT+03:00) Istanbul', name: 'Istanbul', iana: 'Europe/Istanbul' },
  { label: '(GMT+03:00) Kuwait', name: 'Kuwait', iana: 'Asia/Kuwait' },
  { label: '(GMT+03:00) Minsk', name: 'Minsk', iana: 'Europe/Minsk' },
  { label: '(GMT+03:00) Moscow', name: 'Moscow', iana: 'Europe/Moscow' },
  { label: '(GMT+03:00) Nairobi', name: 'Nairobi', iana: 'Africa/Nairobi' },
  { label: '(GMT+03:00) Riyadh', name: 'Riyadh', iana: 'Asia/Riyadh' },
  { label: '(GMT+03:00) St. Petersburg', name: 'St. Petersburg', iana: 'Europe/Moscow' },
  { label: '(GMT+03:00) Volgograd', name: 'Volgograd', iana: 'Europe/Volgograd' },
  { label: '(GMT+03:30) Tehran', name: 'Tehran', iana: 'Asia/Tehran' },
  { label: '(GMT+04:00) Abu Dhabi', name: 'Abu Dhabi', iana: 'Asia/Muscat' },
  { label: '(GMT+04:00) Baku', name: 'Baku', iana: 'Asia/Baku' },
  { label: '(GMT+04:00) Muscat', name: 'Muscat', iana: 'Asia/Muscat' },
  { label: '(GMT+04:00) Samara', name: 'Samara', iana: 'Europe/Samara' },
  { label: '(GMT+04:00) Tbilisi', name: 'Tbilisi', iana: 'Asia/Tbilisi' },
  { label: '(GMT+04:00) Yerevan', name: 'Yerevan', iana: 'Asia/Yerevan' },
  { label: '(GMT+04:30) Kabul', name: 'Kabul', iana: 'Asia/Kabul' },
  { label: '(GMT+05:00) Almaty', name: 'Almaty', iana: 'Asia/Almaty' },
  { label: '(GMT+05:00) Astana', name: 'Astana', iana: 'Asia/Almaty' },
  { label: '(GMT+05:00) Ekaterinburg', name: 'Ekaterinburg', iana: 'Asia/Yekaterinburg' },
  { label: '(GMT+05:00) Islamabad', name: 'Islamabad', iana: 'Asia/Karachi' },
  { label: '(GMT+05:00) Karachi', name: 'Karachi', iana: 'Asia/Karachi' },
  { label: '(GMT+05:00) Tashkent', name: 'Tashkent', iana: 'Asia/Tashkent' },
  { label: '(GMT+05:30) Chennai', name: 'Chennai', iana: 'Asia/Kolkata' },
  { label: '(GMT+05:30) Kolkata', name: 'Kolkata', iana: 'Asia/Kolkata' },
  { label: '(GMT+05:30) Mumbai', name: 'Mumbai', iana: 'Asia/Kolkata' },
  { label: '(GMT+05:30) New Delhi', name: 'New Delhi', iana: 'Asia/Kolkata' },
  { label: '(GMT+05:30) Sri Jayawardenepura', name: 'Sri Jayawardenepura', iana: 'Asia/Colombo' },
  { label: '(GMT+05:45) Kathmandu', name: 'Kathmandu', iana: 'Asia/Kathmandu' },
  { label: '(GMT+06:00) Dhaka', name: 'Dhaka', iana: 'Asia/Dhaka' },
  { label: '(GMT+06:00) Urumqi', name: 'Urumqi', iana: 'Asia/Urumqi' },
  { label: '(GMT+06:30) Rangoon', name: 'Rangoon', iana: 'Asia/Rangoon' },
  { label: '(GMT+07:00) Bangkok', name: 'Bangkok', iana: 'Asia/Bangkok' },
  { label: '(GMT+07:00) Hanoi', name: 'Hanoi', iana: 'Asia/Bangkok' },
  { label: '(GMT+07:00) Jakarta', name: 'Jakarta', iana: 'Asia/Jakarta' },
  { label: '(GMT+07:00) Krasnoyarsk', name: 'Krasnoyarsk', iana: 'Asia/Krasnoyarsk' },
  { label: '(GMT+07:00) Novosibirsk', name: 'Novosibirsk', iana: 'Asia/Novosibirsk' },
  { label: '(GMT+08:00) Beijing', name: 'Beijing', iana: 'Asia/Shanghai' },
  { label: '(GMT+08:00) Chongqing', name: 'Chongqing', iana: 'Asia/Chongqing' },
  { label: '(GMT+08:00) Hong Kong', name: 'Hong Kong', iana: 'Asia/Hong_Kong' },
  { label: '(GMT+08:00) Irkutsk', name: 'Irkutsk', iana: 'Asia/Irkutsk' },
  { label: '(GMT+08:00) Kuala Lumpur', name: 'Kuala Lumpur', iana: 'Asia/Kuala_Lumpur' },
  { label: '(GMT+08:00) Perth', name: 'Perth', iana: 'Australia/Perth' },
  { label: '(GMT+08:00) Singapore', name: 'Singapore', iana: 'Asia/Singapore' },
  { label: '(GMT+08:00) Taipei', name: 'Taipei', iana: 'Asia/Taipei' },
  { label: '(GMT+08:00) Ulaanbaatar', name: 'Ulaanbaatar', iana: 'Asia/Ulaanbaatar' },
  { label: '(GMT+09:00) Osaka', name: 'Osaka', iana: 'Asia/Tokyo' },
  { label: '(GMT+09:00) Sapporo', name: 'Sapporo', iana: 'Asia/Tokyo' },
  { label: '(GMT+09:00) Seoul', name: 'Seoul', iana: 'Asia/Seoul' },
  { label: '(GMT+09:00) Tokyo', name: 'Tokyo', iana: 'Asia/Tokyo' },
  { label: '(GMT+09:00) Yakutsk', name: 'Yakutsk', iana: 'Asia/Yakutsk' },
  { label: '(GMT+09:30) Adelaide', name: 'Adelaide', iana: 'Australia/Adelaide' },
  { label: '(GMT+09:30) Darwin', name: 'Darwin', iana: 'Australia/Darwin' },
  { label: '(GMT+10:00) Brisbane', name: 'Brisbane', iana: 'Australia/Brisbane' },
  { label: '(GMT+10:00) Canberra', name: 'Canberra', iana: 'Australia/Canberra' },
  { label: '(GMT+10:00) Guam', name: 'Guam', iana: 'Pacific/Guam' },
  { label: '(GMT+10:00) Hobart', name: 'Hobart', iana: 'Australia/Hobart' },
  { label: '(GMT+10:00) Melbourne', name: 'Melbourne', iana: 'Australia/Melbourne' },
  { label: '(GMT+10:00) Port Moresby', name: 'Port Moresby', iana: 'Pacific/Port_Moresby' },
  { label: '(GMT+10:00) Sydney', name: 'Sydney', iana: 'Australia/Sydney' },
  { label: '(GMT+10:00) Vladivostok', name: 'Vladivostok', iana: 'Asia/Vladivostok' },
  { label: '(GMT+11:00) Magadan', name: 'Magadan', iana: 'Asia/Magadan' },
  { label: '(GMT+11:00) New Caledonia', name: 'New Caledonia', iana: 'Pacific/Noumea' },
  { label: '(GMT+11:00) Solomon Is.', name: 'Solomon Is.', iana: 'Pacific/Guadalcanal' },
  { label: '(GMT+11:00) Srednekolymsk', name: 'Srednekolymsk', iana: 'Asia/Srednekolymsk' },
  { label: '(GMT+12:00) Auckland', name: 'Auckland', iana: 'Pacific/Auckland' },
  { label: '(GMT+12:00) Fiji', name: 'Fiji', iana: 'Pacific/Fiji' },
  { label: '(GMT+12:00) Kamchatka', name: 'Kamchatka', iana: 'Asia/Kamchatka' },
  { label: '(GMT+12:00) Marshall Is.', name: 'Marshall Is.', iana: 'Pacific/Majuro' },
  { label: '(GMT+12:00) Wellington', name: 'Wellington', iana: 'Pacific/Auckland' },
  { label: '(GMT+12:45) Chatham Is.', name: 'Chatham Is.', iana: 'Pacific/Chatham' },
  { label: "(GMT+13:00) Nuku'alofa", name: "Nuku'alofa", iana: 'Pacific/Tongatapu' },
  { label: '(GMT+13:00) Samoa', name: 'Samoa', iana: 'Pacific/Apia' },
  { label: '(GMT+13:00) Tokelau Is.', name: 'Tokelau Is.', iana: 'Pacific/Fakaofo' },
];
