/** OG's select values and labels, in their original order. */
export const collectionFields = [
  {
    key: 'media_type',
    label: 'Format',
    options: [
      ['digital', 'Digital'],
      ['bluray', 'Blu-ray'],
      ['hddvd', 'HD DVD'],
      ['dvd', 'DVD'],
      ['laserdisc', 'LaserDisc'],
      ['vhs', 'VHS'],
      ['betamax', 'Betamax'],
      ['vcd', 'Video CD'],
    ],
  },
  {
    key: 'resolution',
    label: 'Resolution',
    options: [
      ['uhd_4k', '4K'],
      ['hd_1080p', '1080p'],
      ['hd_1080i', '1080i'],
      ['hd_720p', '720p'],
      ['sd_480p', '480p'],
      ['sd_480i', '480i'],
      ['sd_576p', '576p'],
      ['sd_576i', '576i'],
    ],
  },
  {
    key: 'hdr',
    label: 'HDR',
    options: [['dolby_vision', 'Dolby Vision'], ['hdr10', 'HDR10'], ['hdr10_plus', 'HDR10+'], ['hlg', 'HLG']],
  },
  { key: '3d', label: '3D', options: [['true', 'Yes']], empty: 'No' },
  {
    key: 'audio',
    label: 'Audio',
    options: [
      ['dolby_digital', 'Dolby Digital'],
      ['dolby_digital_plus', 'Dolby Digital+'],
      ['dolby_digital_plus_atmos', 'Dolby Digital+ Atmos'],
      ['dolby_truehd', 'Dolby TrueHD'],
      ['dolby_atmos', 'Dolby TrueHD Atmos'],
      ['dolby_prologic', 'Dolby Pro-logic'],
      ['dts', 'DTS'],
      ['dts_ma', 'DTS-HD MA'],
      ['dts_hr', 'DTS-HD HR'],
      ['dts_x', 'DTS:X'],
      ['auro_3d', 'Auro-3D'],
      ['mp3', 'MP3'],
      ['mp2', 'MP2'],
      ['aac', 'AAC'],
      ['lpcm', 'LPCM'],
      ['ogg', 'Ogg Vorbis'],
      ['ogg_opus', 'Ogg Opus'],
      ['wma', 'WMA'],
      ['flac', 'Flac'],
    ],
  },
  {
    key: 'audio_channels',
    label: 'Channels',
    options: [
      '10.1',
      '9.1',
      '7.1',
      '7.1.2',
      '7.1.4',
      '6.1',
      '5.1',
      '5.1.2',
      '5.1.4',
      '5.0',
      '4.1',
      '4.0',
      '3.1',
      '3.0',
      '2.1',
      '2.0',
      '1.0',
    ].map((value) => [value, value]),
  },
] as const;
